// Client-side synonym map: variant -> canonical.
// Mirrors the subset that matters for user-typed pantry input so that
// "scallion", "coriander", "aubergine" etc. all resolve to the same
// canonical name used in the recipe corpus.
export const SYNONYMS = {
  'scallion': 'green onion',
  'scallions': 'green onion',
  'spring onion': 'green onion',
  'spring onions': 'green onion',
  'green onions': 'green onion',
  'coriander leaves': 'cilantro',
  'coriander': 'cilantro',
  'fresh coriander': 'cilantro',
  'aubergine': 'eggplant',
  'aubergines': 'eggplant',
  'brinjal': 'eggplant',
  'capsicum': 'bell pepper',
  'capsicums': 'bell pepper',
  'courgette': 'zucchini',
  'courgettes': 'zucchini',
  'garbanzo beans': 'chickpeas',
  'garbanzos': 'chickpeas',
  'chana': 'chickpeas',
  'chick peas': 'chickpeas',
  'chickpea': 'chickpeas',
  'plum tomatoes': 'canned tomatoes',
  'tinned tomatoes': 'canned tomatoes',
  'chopped tomatoes': 'canned tomatoes',
  'crushed tomatoes': 'canned tomatoes',
  'coriander powder': 'ground coriander',
  'cumin powder': 'ground cumin',
  'jeera': 'cumin seeds',
  'haldi': 'turmeric',
  'turmeric powder': 'turmeric',
  'chilli powder': 'chili powder',
  'red chilli powder': 'chili powder',
  'chilli flakes': 'chili flakes',
  'red pepper flakes': 'chili flakes',
  'crushed red pepper': 'chili flakes',
  'green chilli': 'green chili',
  'green chillies': 'green chili',
  'green chilies': 'green chili',
  'rocket': 'arugula',
  'prawns': 'shrimp',
  'prawn': 'shrimp',
  'minced beef': 'ground beef',
  'beef mince': 'ground beef',
  'minced pork': 'ground pork',
  'pork mince': 'ground pork',
  'minced lamb': 'ground lamb',
  'lamb mince': 'ground lamb',
  'chicken mince': 'ground chicken',
  'minced chicken': 'ground chicken',
  'plain flour': 'all-purpose flour',
  'maida': 'all-purpose flour',
  'bicarbonate of soda': 'baking soda',
  'bicarb': 'baking soda',
  'caster sugar': 'sugar',
  'granulated sugar': 'sugar',
  'white sugar': 'sugar',
  'double cream': 'heavy cream',
  'whipping cream': 'heavy cream',
  'natural yogurt': 'plain yogurt',
  'natural yoghurt': 'plain yogurt',
  'yoghurt': 'yogurt',
  'curd': 'plain yogurt',
  'soured cream': 'sour cream',
  'gram flour': 'chickpea flour',
  'besan': 'chickpea flour',
  'corn flour': 'cornstarch',
  'cornflour': 'cornstarch',
  'mangetout': 'snow peas',
  'sultanas': 'raisins',
  'beetroot': 'beet',
  'peppers': 'bell pepper',
  'red pepper': 'red bell pepper',
  'green pepper': 'green bell pepper',
  'kidney beans': 'red kidney beans',
  'rajma': 'red kidney beans',
  'toor dal': 'split pigeon peas',
  'arhar dal': 'split pigeon peas',
  'moong dal': 'split mung beans',
  'masoor dal': 'red lentils',
  'red lentil': 'red lentils',
  'flat leaf parsley': 'parsley',
  'flat-leaf parsley': 'parsley',
  'soy': 'soy sauce',
  'light soy sauce': 'soy sauce',
  'dark soy sauce': 'soy sauce',
  'tamari': 'soy sauce',
  'groundnut oil': 'peanut oil',
  'sunflower oil': 'vegetable oil',
  'rapeseed oil': 'vegetable oil',
  'canola oil': 'vegetable oil',
  'clarified butter': 'ghee',
  'extra virgin olive oil': 'olive oil',
  'kosher salt': 'salt',
  'sea salt': 'salt',
  'table salt': 'salt',
  'freshly ground black pepper': 'black pepper',
  'ground black pepper': 'black pepper',
  'runny honey': 'honey',
  'cider vinegar': 'apple cider vinegar',
  'rice wine vinegar': 'rice vinegar',
  'tomato purée': 'tomato paste',
  'tomato puree': 'tomato paste',
  'dijon': 'dijon mustard',
  'desiccated coconut': 'shredded coconut',
  'rice vermicelli': 'rice noodles',
  'vermicelli': 'rice noodles',
  'penne': 'penne pasta',
  'fusilli': 'fusilli pasta',
  'basmati': 'basmati rice',
  'white rice': 'long-grain white rice',
  'long-grain rice': 'long-grain white rice',
  'streaky bacon': 'bacon',
  'back bacon': 'bacon',
  'feta cheese': 'feta',
  'parmesan cheese': 'parmesan',
  'cheddar cheese': 'cheddar',
  'mozzarella cheese': 'mozzarella',
  'corn tortillas': 'corn tortilla',
  'flour tortilla': 'tortilla',
  'flour tortillas': 'tortilla',
};

export function canon(name) {
  const n = String(name).trim().toLowerCase().replace(/\s+/g, ' ');
  return SYNONYMS[n] || n;
}
